### ISSUE TITLE
Feature:  Clearer instructions for how to add to Anwsers  and Questions json file.

### ISSUE THREAD

**Issue by Tc2r1** [Tc2r1/DevInterview_Questions#22]
### Is your feature request related to a problem? Please describe.

I believe that the instructions inside the answers.json and questions.json file are confusing. 

### Describe the solution you'd like

I would like someone to refactor the answers within the two files above to reflect a better understanding of what is needed. 

### Describe alternatives you've considered

The files should contain examples of correct syntax.

**Comment by AndroidLion48** [comment]
Thanks for the Task!
